// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadingCaseImages.DB;

#nullable disable

namespace UploadingCaseImages.DB.Migrations
{
    [DbContext(typeof(UploadingCaseImagesContext))]
    partial class UploadingCaseImagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UploadingCaseImages.DB.Model.Anatomy", b =>
                {
                    b.Property<int>("AnatomyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnatomyId"));

                    b.Property<string>("AnatomyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnatomyId");

                    b.ToTable("Anatomy");
                });

            modelBuilder.Entity("UploadingCaseImages.DB.Model.CaseImage", b =>
                {
                    b.Property<int>("CaseImageId")
                        .HasColumnType("int");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CasePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientCaseId")
                        .HasColumnType("int");

                    b.HasKey("CaseImageId");

                    b.ToTable("CaseImage");
                });

            modelBuilder.Entity("UploadingCaseImages.DB.Model.PatientCase", b =>
                {
                    b.Property<int>("PatientCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientCaseId"));

                    b.Property<int>("AnatomyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientCaseId");

                    b.HasIndex("AnatomyId");

                    b.ToTable("PatientCase");
                });

            modelBuilder.Entity("UploadingCaseImages.DB.Model.CaseImage", b =>
                {
                    b.HasOne("UploadingCaseImages.DB.Model.PatientCase", "PatientCase")
                        .WithMany("CaseImages")
                        .HasForeignKey("CaseImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientCase");
                });

            modelBuilder.Entity("UploadingCaseImages.DB.Model.PatientCase", b =>
                {
                    b.HasOne("UploadingCaseImages.DB.Model.Anatomy", "Anatomy")
                        .WithMany()
                        .HasForeignKey("AnatomyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anatomy");
                });

            modelBuilder.Entity("UploadingCaseImages.DB.Model.PatientCase", b =>
                {
                    b.Navigation("CaseImages");
                });
#pragma warning restore 612, 618
        }
    }
}
