//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadingCaseImages.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UploadingCaseImages.Service.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Id not valid.
        /// </summary>
        public static string AppIdNotValid {
            get {
                return ResourceManager.GetString("AppIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Product Already Has Quota.
        /// </summary>
        public static string DigitalProductAlreadyHasQuota {
            get {
                return ResourceManager.GetString("DigitalProductAlreadyHasQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Product Does Not Have Quota To Update.
        /// </summary>
        public static string DigitalProductDoesnotHaveQuotaToUpdate {
            get {
                return ResourceManager.GetString("DigitalProductDoesnotHaveQuotaToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Already Exists.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Role Code.
        /// </summary>
        public static string DuplicateRoleCode {
            get {
                return ResourceManager.GetString("DuplicateRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Role Name.
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Product Feature Is Already Configured In This Country.
        /// </summary>
        public static string FeatureAlreadyConfigured {
            get {
                return ResourceManager.GetString("FeatureAlreadyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Data!.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Quota.
        /// </summary>
        public static string InsufficientQuota {
            get {
                return ResourceManager.GetString("InsufficientQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Cannot Be Empty!.
        /// </summary>
        public static string MessageCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vodafone Account Linked To This Product Feature.
        /// </summary>
        public static string NoVodafoneAccountLinkedToThisProductFeature {
            get {
                return ResourceManager.GetString("NoVodafoneAccountLinkedToThisProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Respond WIth Bad Request!.
        /// </summary>
        public static string ProviderRespondWIthBadRequest {
            get {
                return ResourceManager.GetString("ProviderRespondWIthBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Not Found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Already Assignd To This User.
        /// </summary>
        public static string RolesAlreadyAssigndToThisUser {
            get {
                return ResourceManager.GetString("RolesAlreadyAssigndToThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Not Found.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms have not been sent!.
        /// </summary>
        public static string SmsNotSent {
            get {
                return ResourceManager.GetString("SmsNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Provider Not Found!.
        /// </summary>
        public static string SMSProviderNotFound {
            get {
                return ResourceManager.GetString("SMSProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical failure.
        /// </summary>
        public static string TechnicalFailure {
            get {
                return ResourceManager.GetString("TechnicalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role Has Users Assigned To It.
        /// </summary>
        public static string ThisRoleHasUsers {
            get {
                return ResourceManager.GetString("ThisRoleHasUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Doesnot Have These Roles.
        /// </summary>
        public static string UserAlreadyDoesnotHaveTheseRoles {
            get {
                return ResourceManager.GetString("UserAlreadyDoesnotHaveTheseRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Authorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Linked To This Digital Product.
        /// </summary>
        public static string UserNotLinkedToThisDigitalProduct {
            get {
                return ResourceManager.GetString("UserNotLinkedToThisDigitalProduct", resourceCulture);
            }
        }
    }
}
